/*
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package org.projektas.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class MMKProposalProvider extends AbstractMMKProposalProvider {
}
