/*
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package org.projektas.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMMKScopeProvider extends DelegatingScopeProvider {
}
