/*
 * generated by Xtext 2.10.0
 */
package org.projektas.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMMKScopeProvider extends DelegatingScopeProvider {
}
