/**
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package org.projektas.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.projektas.ui.AbstractMMKUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MMKUiModule extends AbstractMMKUiModule {
  public MMKUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
