/**
 * generated by Xtext 2.10.0
 */
package org.projektas.mMK;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.projektas.mMK.MMKFactory
 * @model kind="package"
 * @generated
 */
public interface MMKPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "mMK";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.projektas.org/MMK";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "mMK";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MMKPackage eINSTANCE = org.projektas.mMK.impl.MMKPackageImpl.init();

  /**
   * The meta object id for the '{@link org.projektas.mMK.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.projektas.mMK.impl.ModelImpl
   * @see org.projektas.mMK.impl.MMKPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.projektas.mMK.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.projektas.mMK.impl.AbstractElementImpl
   * @see org.projektas.mMK.impl.MMKPackageImpl#getAbstractElement()
   * @generated
   */
  int ABSTRACT_ELEMENT = 1;

  /**
   * The number of structural features of the '<em>Abstract Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.projektas.mMK.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.projektas.mMK.impl.StatementImpl
   * @see org.projektas.mMK.impl.MMKPackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 2;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.projektas.mMK.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.projektas.mMK.impl.ExpressionImpl
   * @see org.projektas.mMK.impl.MMKPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 3;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.projektas.mMK.impl.GetLineExpressionImpl <em>Get Line Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.projektas.mMK.impl.GetLineExpressionImpl
   * @see org.projektas.mMK.impl.MMKPackageImpl#getGetLineExpression()
   * @generated
   */
  int GET_LINE_EXPRESSION = 4;

  /**
   * The feature id for the '<em><b>What</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GET_LINE_EXPRESSION__WHAT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Get Line Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GET_LINE_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.projektas.mMK.impl.GetNumExpressionImpl <em>Get Num Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.projektas.mMK.impl.GetNumExpressionImpl
   * @see org.projektas.mMK.impl.MMKPackageImpl#getGetNumExpression()
   * @generated
   */
  int GET_NUM_EXPRESSION = 5;

  /**
   * The feature id for the '<em><b>What</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GET_NUM_EXPRESSION__WHAT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Get Num Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GET_NUM_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.projektas.mMK.impl.PrintExpressionImpl <em>Print Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.projektas.mMK.impl.PrintExpressionImpl
   * @see org.projektas.mMK.impl.MMKPackageImpl#getPrintExpression()
   * @generated
   */
  int PRINT_EXPRESSION = 6;

  /**
   * The feature id for the '<em><b>What</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT_EXPRESSION__WHAT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Print Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.projektas.mMK.impl.VariableImpl <em>Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.projektas.mMK.impl.VariableImpl
   * @see org.projektas.mMK.impl.MMKPackageImpl#getVariable()
   * @generated
   */
  int VARIABLE = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__NAME = 0;

  /**
   * The number of structural features of the '<em>Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.projektas.mMK.impl.ExprBodyImpl <em>Expr Body</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.projektas.mMK.impl.ExprBodyImpl
   * @see org.projektas.mMK.impl.MMKPackageImpl#getExprBody()
   * @generated
   */
  int EXPR_BODY = 8;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_BODY__EXPR = 0;

  /**
   * The number of structural features of the '<em>Expr Body</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_BODY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.projektas.mMK.impl.FactorExpressionImpl <em>Factor Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.projektas.mMK.impl.FactorExpressionImpl
   * @see org.projektas.mMK.impl.MMKPackageImpl#getFactorExpression()
   * @generated
   */
  int FACTOR_EXPRESSION = 9;

  /**
   * The feature id for the '<em><b>L</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACTOR_EXPRESSION__L = 0;

  /**
   * The feature id for the '<em><b>A</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACTOR_EXPRESSION__A = 1;

  /**
   * The number of structural features of the '<em>Factor Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACTOR_EXPRESSION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.projektas.mMK.impl.ArithmeticsImpl <em>Arithmetics</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.projektas.mMK.impl.ArithmeticsImpl
   * @see org.projektas.mMK.impl.MMKPackageImpl#getArithmetics()
   * @generated
   */
  int ARITHMETICS = 10;

  /**
   * The feature id for the '<em><b>M</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITHMETICS__M = 0;

  /**
   * The feature id for the '<em><b>R</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITHMETICS__R = 1;

  /**
   * The number of structural features of the '<em>Arithmetics</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITHMETICS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.projektas.mMK.impl.PrimaryImpl <em>Primary</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.projektas.mMK.impl.PrimaryImpl
   * @see org.projektas.mMK.impl.MMKPackageImpl#getPrimary()
   * @generated
   */
  int PRIMARY = 11;

  /**
   * The number of structural features of the '<em>Primary</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMARY_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.projektas.mMK.impl.FactorExprImpl <em>Factor Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.projektas.mMK.impl.FactorExprImpl
   * @see org.projektas.mMK.impl.MMKPackageImpl#getFactorExpr()
   * @generated
   */
  int FACTOR_EXPR = 12;

  /**
   * The feature id for the '<em><b>L</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACTOR_EXPR__L = PRIMARY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>A</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACTOR_EXPR__A = PRIMARY_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Factor Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACTOR_EXPR_FEATURE_COUNT = PRIMARY_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.projektas.mMK.impl.UnaryExpressionImpl <em>Unary Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.projektas.mMK.impl.UnaryExpressionImpl
   * @see org.projektas.mMK.impl.MMKPackageImpl#getUnaryExpression()
   * @generated
   */
  int UNARY_EXPRESSION = 13;

  /**
   * The feature id for the '<em><b>Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_EXPRESSION__VAL = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Us</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_EXPRESSION__US = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Unary Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.projektas.mMK.impl.ValueImpl <em>Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.projektas.mMK.impl.ValueImpl
   * @see org.projektas.mMK.impl.MMKPackageImpl#getValue()
   * @generated
   */
  int VALUE = 14;

  /**
   * The feature id for the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE__VAR = 0;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE__VAL = 1;

  /**
   * The number of structural features of the '<em>Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.projektas.mMK.impl.CreationExpressionImpl <em>Creation Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.projektas.mMK.impl.CreationExpressionImpl
   * @see org.projektas.mMK.impl.MMKPackageImpl#getCreationExpression()
   * @generated
   */
  int CREATION_EXPRESSION = 15;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATION_EXPRESSION__TYPE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATION_EXPRESSION__NAME = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATION_EXPRESSION__VAL = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Creation Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATION_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.projektas.mMK.impl.AssignmentExpressionImpl <em>Assignment Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.projektas.mMK.impl.AssignmentExpressionImpl
   * @see org.projektas.mMK.impl.MMKPackageImpl#getAssignmentExpression()
   * @generated
   */
  int ASSIGNMENT_EXPRESSION = 16;

  /**
   * The feature id for the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT_EXPRESSION__NAME = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT_EXPRESSION__VAL = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Assignment Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.projektas.mMK.impl.ConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.projektas.mMK.impl.ConditionImpl
   * @see org.projektas.mMK.impl.MMKPackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 17;

  /**
   * The feature id for the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__COND = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Then</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__THEN = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Else</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__ELSE = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.projektas.mMK.impl.ConditionalExprImpl <em>Conditional Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.projektas.mMK.impl.ConditionalExprImpl
   * @see org.projektas.mMK.impl.MMKPackageImpl#getConditionalExpr()
   * @generated
   */
  int CONDITIONAL_EXPR = 18;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL_EXPR__LEFT = 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL_EXPR__OP = 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL_EXPR__RIGHT = 2;

  /**
   * The number of structural features of the '<em>Conditional Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL_EXPR_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.projektas.mMK.impl.OperationImpl <em>Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.projektas.mMK.impl.OperationImpl
   * @see org.projektas.mMK.impl.MMKPackageImpl#getOperation()
   * @generated
   */
  int OPERATION = 19;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__NAME = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Params</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__PARAMS = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__TYPE = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__BODY = ABSTRACT_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.projektas.mMK.impl.WhileExpressionImpl <em>While Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.projektas.mMK.impl.WhileExpressionImpl
   * @see org.projektas.mMK.impl.MMKPackageImpl#getWhileExpression()
   * @generated
   */
  int WHILE_EXPRESSION = 20;

  /**
   * The feature id for the '<em><b>End</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_EXPRESSION__END = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Loop</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_EXPRESSION__LOOP = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>While Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_EXPRESSION_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link org.projektas.mMK.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.projektas.mMK.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.projektas.mMK.Model#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.projektas.mMK.Model#getElements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Elements();

  /**
   * Returns the meta object for class '{@link org.projektas.mMK.AbstractElement <em>Abstract Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Element</em>'.
   * @see org.projektas.mMK.AbstractElement
   * @generated
   */
  EClass getAbstractElement();

  /**
   * Returns the meta object for class '{@link org.projektas.mMK.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see org.projektas.mMK.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for class '{@link org.projektas.mMK.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see org.projektas.mMK.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link org.projektas.mMK.GetLineExpression <em>Get Line Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Get Line Expression</em>'.
   * @see org.projektas.mMK.GetLineExpression
   * @generated
   */
  EClass getGetLineExpression();

  /**
   * Returns the meta object for the containment reference '{@link org.projektas.mMK.GetLineExpression#getWhat <em>What</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>What</em>'.
   * @see org.projektas.mMK.GetLineExpression#getWhat()
   * @see #getGetLineExpression()
   * @generated
   */
  EReference getGetLineExpression_What();

  /**
   * Returns the meta object for class '{@link org.projektas.mMK.GetNumExpression <em>Get Num Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Get Num Expression</em>'.
   * @see org.projektas.mMK.GetNumExpression
   * @generated
   */
  EClass getGetNumExpression();

  /**
   * Returns the meta object for the containment reference '{@link org.projektas.mMK.GetNumExpression#getWhat <em>What</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>What</em>'.
   * @see org.projektas.mMK.GetNumExpression#getWhat()
   * @see #getGetNumExpression()
   * @generated
   */
  EReference getGetNumExpression_What();

  /**
   * Returns the meta object for class '{@link org.projektas.mMK.PrintExpression <em>Print Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Print Expression</em>'.
   * @see org.projektas.mMK.PrintExpression
   * @generated
   */
  EClass getPrintExpression();

  /**
   * Returns the meta object for the containment reference '{@link org.projektas.mMK.PrintExpression#getWhat <em>What</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>What</em>'.
   * @see org.projektas.mMK.PrintExpression#getWhat()
   * @see #getPrintExpression()
   * @generated
   */
  EReference getPrintExpression_What();

  /**
   * Returns the meta object for class '{@link org.projektas.mMK.Variable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable</em>'.
   * @see org.projektas.mMK.Variable
   * @generated
   */
  EClass getVariable();

  /**
   * Returns the meta object for the attribute '{@link org.projektas.mMK.Variable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.projektas.mMK.Variable#getName()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Name();

  /**
   * Returns the meta object for class '{@link org.projektas.mMK.ExprBody <em>Expr Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr Body</em>'.
   * @see org.projektas.mMK.ExprBody
   * @generated
   */
  EClass getExprBody();

  /**
   * Returns the meta object for the containment reference list '{@link org.projektas.mMK.ExprBody#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expr</em>'.
   * @see org.projektas.mMK.ExprBody#getExpr()
   * @see #getExprBody()
   * @generated
   */
  EReference getExprBody_Expr();

  /**
   * Returns the meta object for class '{@link org.projektas.mMK.FactorExpression <em>Factor Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Factor Expression</em>'.
   * @see org.projektas.mMK.FactorExpression
   * @generated
   */
  EClass getFactorExpression();

  /**
   * Returns the meta object for the containment reference '{@link org.projektas.mMK.FactorExpression#getL <em>L</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>L</em>'.
   * @see org.projektas.mMK.FactorExpression#getL()
   * @see #getFactorExpression()
   * @generated
   */
  EReference getFactorExpression_L();

  /**
   * Returns the meta object for the containment reference list '{@link org.projektas.mMK.FactorExpression#getA <em>A</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>A</em>'.
   * @see org.projektas.mMK.FactorExpression#getA()
   * @see #getFactorExpression()
   * @generated
   */
  EReference getFactorExpression_A();

  /**
   * Returns the meta object for class '{@link org.projektas.mMK.Arithmetics <em>Arithmetics</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Arithmetics</em>'.
   * @see org.projektas.mMK.Arithmetics
   * @generated
   */
  EClass getArithmetics();

  /**
   * Returns the meta object for the attribute '{@link org.projektas.mMK.Arithmetics#getM <em>M</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>M</em>'.
   * @see org.projektas.mMK.Arithmetics#getM()
   * @see #getArithmetics()
   * @generated
   */
  EAttribute getArithmetics_M();

  /**
   * Returns the meta object for the containment reference '{@link org.projektas.mMK.Arithmetics#getR <em>R</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>R</em>'.
   * @see org.projektas.mMK.Arithmetics#getR()
   * @see #getArithmetics()
   * @generated
   */
  EReference getArithmetics_R();

  /**
   * Returns the meta object for class '{@link org.projektas.mMK.Primary <em>Primary</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Primary</em>'.
   * @see org.projektas.mMK.Primary
   * @generated
   */
  EClass getPrimary();

  /**
   * Returns the meta object for class '{@link org.projektas.mMK.FactorExpr <em>Factor Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Factor Expr</em>'.
   * @see org.projektas.mMK.FactorExpr
   * @generated
   */
  EClass getFactorExpr();

  /**
   * Returns the meta object for the containment reference '{@link org.projektas.mMK.FactorExpr#getL <em>L</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>L</em>'.
   * @see org.projektas.mMK.FactorExpr#getL()
   * @see #getFactorExpr()
   * @generated
   */
  EReference getFactorExpr_L();

  /**
   * Returns the meta object for the containment reference list '{@link org.projektas.mMK.FactorExpr#getA <em>A</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>A</em>'.
   * @see org.projektas.mMK.FactorExpr#getA()
   * @see #getFactorExpr()
   * @generated
   */
  EReference getFactorExpr_A();

  /**
   * Returns the meta object for class '{@link org.projektas.mMK.UnaryExpression <em>Unary Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Unary Expression</em>'.
   * @see org.projektas.mMK.UnaryExpression
   * @generated
   */
  EClass getUnaryExpression();

  /**
   * Returns the meta object for the containment reference '{@link org.projektas.mMK.UnaryExpression#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Val</em>'.
   * @see org.projektas.mMK.UnaryExpression#getVal()
   * @see #getUnaryExpression()
   * @generated
   */
  EReference getUnaryExpression_Val();

  /**
   * Returns the meta object for the attribute '{@link org.projektas.mMK.UnaryExpression#getUs <em>Us</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Us</em>'.
   * @see org.projektas.mMK.UnaryExpression#getUs()
   * @see #getUnaryExpression()
   * @generated
   */
  EAttribute getUnaryExpression_Us();

  /**
   * Returns the meta object for class '{@link org.projektas.mMK.Value <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Value</em>'.
   * @see org.projektas.mMK.Value
   * @generated
   */
  EClass getValue();

  /**
   * Returns the meta object for the reference '{@link org.projektas.mMK.Value#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Var</em>'.
   * @see org.projektas.mMK.Value#getVar()
   * @see #getValue()
   * @generated
   */
  EReference getValue_Var();

  /**
   * Returns the meta object for the attribute '{@link org.projektas.mMK.Value#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see org.projektas.mMK.Value#getVal()
   * @see #getValue()
   * @generated
   */
  EAttribute getValue_Val();

  /**
   * Returns the meta object for class '{@link org.projektas.mMK.CreationExpression <em>Creation Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Creation Expression</em>'.
   * @see org.projektas.mMK.CreationExpression
   * @generated
   */
  EClass getCreationExpression();

  /**
   * Returns the meta object for the attribute '{@link org.projektas.mMK.CreationExpression#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.projektas.mMK.CreationExpression#getType()
   * @see #getCreationExpression()
   * @generated
   */
  EAttribute getCreationExpression_Type();

  /**
   * Returns the meta object for the containment reference '{@link org.projektas.mMK.CreationExpression#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Name</em>'.
   * @see org.projektas.mMK.CreationExpression#getName()
   * @see #getCreationExpression()
   * @generated
   */
  EReference getCreationExpression_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.projektas.mMK.CreationExpression#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Val</em>'.
   * @see org.projektas.mMK.CreationExpression#getVal()
   * @see #getCreationExpression()
   * @generated
   */
  EReference getCreationExpression_Val();

  /**
   * Returns the meta object for class '{@link org.projektas.mMK.AssignmentExpression <em>Assignment Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assignment Expression</em>'.
   * @see org.projektas.mMK.AssignmentExpression
   * @generated
   */
  EClass getAssignmentExpression();

  /**
   * Returns the meta object for the reference '{@link org.projektas.mMK.AssignmentExpression#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Name</em>'.
   * @see org.projektas.mMK.AssignmentExpression#getName()
   * @see #getAssignmentExpression()
   * @generated
   */
  EReference getAssignmentExpression_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.projektas.mMK.AssignmentExpression#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Val</em>'.
   * @see org.projektas.mMK.AssignmentExpression#getVal()
   * @see #getAssignmentExpression()
   * @generated
   */
  EReference getAssignmentExpression_Val();

  /**
   * Returns the meta object for class '{@link org.projektas.mMK.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see org.projektas.mMK.Condition
   * @generated
   */
  EClass getCondition();

  /**
   * Returns the meta object for the containment reference '{@link org.projektas.mMK.Condition#getCond <em>Cond</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cond</em>'.
   * @see org.projektas.mMK.Condition#getCond()
   * @see #getCondition()
   * @generated
   */
  EReference getCondition_Cond();

  /**
   * Returns the meta object for the containment reference list '{@link org.projektas.mMK.Condition#getThen <em>Then</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Then</em>'.
   * @see org.projektas.mMK.Condition#getThen()
   * @see #getCondition()
   * @generated
   */
  EReference getCondition_Then();

  /**
   * Returns the meta object for the containment reference list '{@link org.projektas.mMK.Condition#getElse <em>Else</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Else</em>'.
   * @see org.projektas.mMK.Condition#getElse()
   * @see #getCondition()
   * @generated
   */
  EReference getCondition_Else();

  /**
   * Returns the meta object for class '{@link org.projektas.mMK.ConditionalExpr <em>Conditional Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Conditional Expr</em>'.
   * @see org.projektas.mMK.ConditionalExpr
   * @generated
   */
  EClass getConditionalExpr();

  /**
   * Returns the meta object for the containment reference '{@link org.projektas.mMK.ConditionalExpr#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.projektas.mMK.ConditionalExpr#getLeft()
   * @see #getConditionalExpr()
   * @generated
   */
  EReference getConditionalExpr_Left();

  /**
   * Returns the meta object for the attribute '{@link org.projektas.mMK.ConditionalExpr#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see org.projektas.mMK.ConditionalExpr#getOp()
   * @see #getConditionalExpr()
   * @generated
   */
  EAttribute getConditionalExpr_Op();

  /**
   * Returns the meta object for the containment reference '{@link org.projektas.mMK.ConditionalExpr#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.projektas.mMK.ConditionalExpr#getRight()
   * @see #getConditionalExpr()
   * @generated
   */
  EReference getConditionalExpr_Right();

  /**
   * Returns the meta object for class '{@link org.projektas.mMK.Operation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation</em>'.
   * @see org.projektas.mMK.Operation
   * @generated
   */
  EClass getOperation();

  /**
   * Returns the meta object for the attribute '{@link org.projektas.mMK.Operation#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.projektas.mMK.Operation#getName()
   * @see #getOperation()
   * @generated
   */
  EAttribute getOperation_Name();

  /**
   * Returns the meta object for the attribute list '{@link org.projektas.mMK.Operation#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Params</em>'.
   * @see org.projektas.mMK.Operation#getParams()
   * @see #getOperation()
   * @generated
   */
  EAttribute getOperation_Params();

  /**
   * Returns the meta object for the attribute '{@link org.projektas.mMK.Operation#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.projektas.mMK.Operation#getType()
   * @see #getOperation()
   * @generated
   */
  EAttribute getOperation_Type();

  /**
   * Returns the meta object for the containment reference '{@link org.projektas.mMK.Operation#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see org.projektas.mMK.Operation#getBody()
   * @see #getOperation()
   * @generated
   */
  EReference getOperation_Body();

  /**
   * Returns the meta object for class '{@link org.projektas.mMK.WhileExpression <em>While Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>While Expression</em>'.
   * @see org.projektas.mMK.WhileExpression
   * @generated
   */
  EClass getWhileExpression();

  /**
   * Returns the meta object for the containment reference '{@link org.projektas.mMK.WhileExpression#getEnd <em>End</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>End</em>'.
   * @see org.projektas.mMK.WhileExpression#getEnd()
   * @see #getWhileExpression()
   * @generated
   */
  EReference getWhileExpression_End();

  /**
   * Returns the meta object for the containment reference list '{@link org.projektas.mMK.WhileExpression#getLoop <em>Loop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Loop</em>'.
   * @see org.projektas.mMK.WhileExpression#getLoop()
   * @see #getWhileExpression()
   * @generated
   */
  EReference getWhileExpression_Loop();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MMKFactory getMMKFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.projektas.mMK.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.projektas.mMK.impl.ModelImpl
     * @see org.projektas.mMK.impl.MMKPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ELEMENTS = eINSTANCE.getModel_Elements();

    /**
     * The meta object literal for the '{@link org.projektas.mMK.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.projektas.mMK.impl.AbstractElementImpl
     * @see org.projektas.mMK.impl.MMKPackageImpl#getAbstractElement()
     * @generated
     */
    EClass ABSTRACT_ELEMENT = eINSTANCE.getAbstractElement();

    /**
     * The meta object literal for the '{@link org.projektas.mMK.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.projektas.mMK.impl.StatementImpl
     * @see org.projektas.mMK.impl.MMKPackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '{@link org.projektas.mMK.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.projektas.mMK.impl.ExpressionImpl
     * @see org.projektas.mMK.impl.MMKPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link org.projektas.mMK.impl.GetLineExpressionImpl <em>Get Line Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.projektas.mMK.impl.GetLineExpressionImpl
     * @see org.projektas.mMK.impl.MMKPackageImpl#getGetLineExpression()
     * @generated
     */
    EClass GET_LINE_EXPRESSION = eINSTANCE.getGetLineExpression();

    /**
     * The meta object literal for the '<em><b>What</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GET_LINE_EXPRESSION__WHAT = eINSTANCE.getGetLineExpression_What();

    /**
     * The meta object literal for the '{@link org.projektas.mMK.impl.GetNumExpressionImpl <em>Get Num Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.projektas.mMK.impl.GetNumExpressionImpl
     * @see org.projektas.mMK.impl.MMKPackageImpl#getGetNumExpression()
     * @generated
     */
    EClass GET_NUM_EXPRESSION = eINSTANCE.getGetNumExpression();

    /**
     * The meta object literal for the '<em><b>What</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GET_NUM_EXPRESSION__WHAT = eINSTANCE.getGetNumExpression_What();

    /**
     * The meta object literal for the '{@link org.projektas.mMK.impl.PrintExpressionImpl <em>Print Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.projektas.mMK.impl.PrintExpressionImpl
     * @see org.projektas.mMK.impl.MMKPackageImpl#getPrintExpression()
     * @generated
     */
    EClass PRINT_EXPRESSION = eINSTANCE.getPrintExpression();

    /**
     * The meta object literal for the '<em><b>What</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRINT_EXPRESSION__WHAT = eINSTANCE.getPrintExpression_What();

    /**
     * The meta object literal for the '{@link org.projektas.mMK.impl.VariableImpl <em>Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.projektas.mMK.impl.VariableImpl
     * @see org.projektas.mMK.impl.MMKPackageImpl#getVariable()
     * @generated
     */
    EClass VARIABLE = eINSTANCE.getVariable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__NAME = eINSTANCE.getVariable_Name();

    /**
     * The meta object literal for the '{@link org.projektas.mMK.impl.ExprBodyImpl <em>Expr Body</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.projektas.mMK.impl.ExprBodyImpl
     * @see org.projektas.mMK.impl.MMKPackageImpl#getExprBody()
     * @generated
     */
    EClass EXPR_BODY = eINSTANCE.getExprBody();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_BODY__EXPR = eINSTANCE.getExprBody_Expr();

    /**
     * The meta object literal for the '{@link org.projektas.mMK.impl.FactorExpressionImpl <em>Factor Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.projektas.mMK.impl.FactorExpressionImpl
     * @see org.projektas.mMK.impl.MMKPackageImpl#getFactorExpression()
     * @generated
     */
    EClass FACTOR_EXPRESSION = eINSTANCE.getFactorExpression();

    /**
     * The meta object literal for the '<em><b>L</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FACTOR_EXPRESSION__L = eINSTANCE.getFactorExpression_L();

    /**
     * The meta object literal for the '<em><b>A</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FACTOR_EXPRESSION__A = eINSTANCE.getFactorExpression_A();

    /**
     * The meta object literal for the '{@link org.projektas.mMK.impl.ArithmeticsImpl <em>Arithmetics</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.projektas.mMK.impl.ArithmeticsImpl
     * @see org.projektas.mMK.impl.MMKPackageImpl#getArithmetics()
     * @generated
     */
    EClass ARITHMETICS = eINSTANCE.getArithmetics();

    /**
     * The meta object literal for the '<em><b>M</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARITHMETICS__M = eINSTANCE.getArithmetics_M();

    /**
     * The meta object literal for the '<em><b>R</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARITHMETICS__R = eINSTANCE.getArithmetics_R();

    /**
     * The meta object literal for the '{@link org.projektas.mMK.impl.PrimaryImpl <em>Primary</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.projektas.mMK.impl.PrimaryImpl
     * @see org.projektas.mMK.impl.MMKPackageImpl#getPrimary()
     * @generated
     */
    EClass PRIMARY = eINSTANCE.getPrimary();

    /**
     * The meta object literal for the '{@link org.projektas.mMK.impl.FactorExprImpl <em>Factor Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.projektas.mMK.impl.FactorExprImpl
     * @see org.projektas.mMK.impl.MMKPackageImpl#getFactorExpr()
     * @generated
     */
    EClass FACTOR_EXPR = eINSTANCE.getFactorExpr();

    /**
     * The meta object literal for the '<em><b>L</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FACTOR_EXPR__L = eINSTANCE.getFactorExpr_L();

    /**
     * The meta object literal for the '<em><b>A</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FACTOR_EXPR__A = eINSTANCE.getFactorExpr_A();

    /**
     * The meta object literal for the '{@link org.projektas.mMK.impl.UnaryExpressionImpl <em>Unary Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.projektas.mMK.impl.UnaryExpressionImpl
     * @see org.projektas.mMK.impl.MMKPackageImpl#getUnaryExpression()
     * @generated
     */
    EClass UNARY_EXPRESSION = eINSTANCE.getUnaryExpression();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UNARY_EXPRESSION__VAL = eINSTANCE.getUnaryExpression_Val();

    /**
     * The meta object literal for the '<em><b>Us</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNARY_EXPRESSION__US = eINSTANCE.getUnaryExpression_Us();

    /**
     * The meta object literal for the '{@link org.projektas.mMK.impl.ValueImpl <em>Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.projektas.mMK.impl.ValueImpl
     * @see org.projektas.mMK.impl.MMKPackageImpl#getValue()
     * @generated
     */
    EClass VALUE = eINSTANCE.getValue();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VALUE__VAR = eINSTANCE.getValue_Var();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALUE__VAL = eINSTANCE.getValue_Val();

    /**
     * The meta object literal for the '{@link org.projektas.mMK.impl.CreationExpressionImpl <em>Creation Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.projektas.mMK.impl.CreationExpressionImpl
     * @see org.projektas.mMK.impl.MMKPackageImpl#getCreationExpression()
     * @generated
     */
    EClass CREATION_EXPRESSION = eINSTANCE.getCreationExpression();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CREATION_EXPRESSION__TYPE = eINSTANCE.getCreationExpression_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CREATION_EXPRESSION__NAME = eINSTANCE.getCreationExpression_Name();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CREATION_EXPRESSION__VAL = eINSTANCE.getCreationExpression_Val();

    /**
     * The meta object literal for the '{@link org.projektas.mMK.impl.AssignmentExpressionImpl <em>Assignment Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.projektas.mMK.impl.AssignmentExpressionImpl
     * @see org.projektas.mMK.impl.MMKPackageImpl#getAssignmentExpression()
     * @generated
     */
    EClass ASSIGNMENT_EXPRESSION = eINSTANCE.getAssignmentExpression();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSIGNMENT_EXPRESSION__NAME = eINSTANCE.getAssignmentExpression_Name();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSIGNMENT_EXPRESSION__VAL = eINSTANCE.getAssignmentExpression_Val();

    /**
     * The meta object literal for the '{@link org.projektas.mMK.impl.ConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.projektas.mMK.impl.ConditionImpl
     * @see org.projektas.mMK.impl.MMKPackageImpl#getCondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '<em><b>Cond</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITION__COND = eINSTANCE.getCondition_Cond();

    /**
     * The meta object literal for the '<em><b>Then</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITION__THEN = eINSTANCE.getCondition_Then();

    /**
     * The meta object literal for the '<em><b>Else</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITION__ELSE = eINSTANCE.getCondition_Else();

    /**
     * The meta object literal for the '{@link org.projektas.mMK.impl.ConditionalExprImpl <em>Conditional Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.projektas.mMK.impl.ConditionalExprImpl
     * @see org.projektas.mMK.impl.MMKPackageImpl#getConditionalExpr()
     * @generated
     */
    EClass CONDITIONAL_EXPR = eINSTANCE.getConditionalExpr();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITIONAL_EXPR__LEFT = eINSTANCE.getConditionalExpr_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITIONAL_EXPR__OP = eINSTANCE.getConditionalExpr_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITIONAL_EXPR__RIGHT = eINSTANCE.getConditionalExpr_Right();

    /**
     * The meta object literal for the '{@link org.projektas.mMK.impl.OperationImpl <em>Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.projektas.mMK.impl.OperationImpl
     * @see org.projektas.mMK.impl.MMKPackageImpl#getOperation()
     * @generated
     */
    EClass OPERATION = eINSTANCE.getOperation();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATION__NAME = eINSTANCE.getOperation_Name();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATION__PARAMS = eINSTANCE.getOperation_Params();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATION__TYPE = eINSTANCE.getOperation_Type();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATION__BODY = eINSTANCE.getOperation_Body();

    /**
     * The meta object literal for the '{@link org.projektas.mMK.impl.WhileExpressionImpl <em>While Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.projektas.mMK.impl.WhileExpressionImpl
     * @see org.projektas.mMK.impl.MMKPackageImpl#getWhileExpression()
     * @generated
     */
    EClass WHILE_EXPRESSION = eINSTANCE.getWhileExpression();

    /**
     * The meta object literal for the '<em><b>End</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHILE_EXPRESSION__END = eINSTANCE.getWhileExpression_End();

    /**
     * The meta object literal for the '<em><b>Loop</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHILE_EXPRESSION__LOOP = eINSTANCE.getWhileExpression_Loop();

  }

} //MMKPackage
