/*
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package org.projektas.ui.tests;

import com.google.inject.Injector;
import mmk.ui.internal.MmkActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MMKUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MmkActivator.getInstance().getInjector("org.projektas.MMK");
	}

}
