/*
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package org.projektas.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.projektas.MMKRuntimeModule
import org.projektas.MMKStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MMKIdeSetup extends MMKStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MMKRuntimeModule, new MMKIdeModule))
	}
	
}
