/*
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package org.projektas.ui;

import com.google.inject.Injector;
import mmk.ui.internal.MmkActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MMKExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MmkActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MmkActivator.getInstance().getInjector(MmkActivator.ORG_PROJEKTAS_MMK);
	}
	
}
