/*
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package org.projektas


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MMKRuntimeModule extends AbstractMMKRuntimeModule {
}
