/*
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package org.projektas.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractMMKValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.projektas.mMK.MMKPackage.eINSTANCE);
		return result;
	}
	
}
