/**
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package org.projektas.ide;

import org.projektas.ide.AbstractMMKIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MMKIdeModule extends AbstractMMKIdeModule {
}
