/**
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package org.projektas.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.projektas.MMKRuntimeModule;
import org.projektas.MMKStandaloneSetup;
import org.projektas.ide.MMKIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MMKIdeSetup extends MMKStandaloneSetup {
  @Override
  public Injector createInjector() {
    MMKRuntimeModule _mMKRuntimeModule = new MMKRuntimeModule();
    MMKIdeModule _mMKIdeModule = new MMKIdeModule();
    return Guice.createInjector(Modules2.mixin(_mMKRuntimeModule, _mMKIdeModule));
  }
}
