/**
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package org.projektas.ui.contentassist;

import org.projektas.ui.contentassist.AbstractMMKProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MMKProposalProvider extends AbstractMMKProposalProvider {
}
