/**
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package org.projektas;

import org.projektas.AbstractMMKRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MMKRuntimeModule extends AbstractMMKRuntimeModule {
}
